[package]
name = "mqtt-client"
version = "0.1.0"
authors = ["Alex Helfet <alex.helfet@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
readme = "README.md"

[dependencies]
bytes = "0.4.0"
env_logger = "0.7.1"
futures-core = "0.3.1"
futures-util = "0.3.1"
log = "0.4.8"
mqttrs = "0.2.0"
structopt = "0.3.5"
tokio = { version = "0.2.2", features = ["dns", "io-util", "macros", "rt-core", "sync", "tcp", "time"] }

[dev-dependencies]
maplit = "1.0.2"